// src/components/AccentButton.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let padding: string = '0px';
    export let sensitive: boolean = true;

    export let click: () => void = () => {};

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--accent-button
        display: inline-block
        cursor: pointer
        text-align: center
        text-decoration: none
        user-select: none
</style>

<button
    style:margin={margin}
    style:padding={padding}
    class={`
        hyperbloomui--accent-button
        hyperbloomui--${currentTheme}--accent-button
    `}
    disabled={!sensitive}
    on:click={click}
>
    <slot />
</button>

// src/components/AccentButton.vue
<script setup>
    import { defineProps } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        padding: String
    });

    const emit = defineEmits([
        'click'
    ]);
</script>

<template>
    <div
        aria-component-id="button"
        :style="`
            margin: ${props.margin ?? '0px'};
            padding: ${props.padding ?? '0px'};
        `"
        :class="`hyperbloomui--button hyperbloomui--${state.hyperbloomui.theme.name}--accent-button`"
        @click="$emit('click')"
    >
        <slot />
    </div>
</template>
