// src/components/LinkBox.vue
<script setup>
    import { defineProps, defineEmits } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        padding: String,
        href: String
    });

    const emit = defineEmits([
        'click'
    ]);
</script>

<style lang="sass">
    .hyperbloomui--link-box
        display: block
        text-align: start
</style>

<template>
    <a
        aria-component-id="link-box"
        :href="props.href ?? '#'"
        :style="`
            margin: ${props.margin ?? '0px'};
            padding: ${props.padding ?? '0px'};
        `"
        :class="`
            hyperbloomui--link-box
            hyperbloomui--${state.hyperbloomui.theme.name}--link-box
        `"
        @click="$emit('click')"
    >
        <slot />
    </a>
</template>

// src/components/LinkBox.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let padding: string = '0px';
    export let href: string = '#';

    export let click: () => void = () => {};

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--link-box
        display: block
        text-align: start
</style>

<a
    href={href}
    style:margin={margin}
    style:padding={padding}
    class={`
        hyperbloomui--link-box
        hyperbloomui--${currentTheme}--link-box
    `}
    on:click={click}
>
    <slot />
</a>
