// src/components/Link.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let padding: string = '0px';
    export let href: string = '#';

    export let click: () => void = () => {};

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--link
        display: block
        text-align: start
</style>

<a
    href={href}
    style:margin={margin}
    style:padding={padding}
    class={`
        hyperbloomui--link
        hyperbloomui--${currentTheme}--link
    `}
    on:click={click}
>
    <slot />
</a>

// src/components/Link.vue
<script setup>
    import { defineProps, defineEmits } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        padding: String,
        href: String
    });

    const emit = defineEmits([
        'click'
    ]);
</script>

<style lang="sass">
    .hyperbloomui--link
        display: block
        text-align: start
</style>

<template>
    <a
        aria-component-id="link"
        :href="props.href ?? '#'"
        :style="`
            margin: ${props.margin ?? '0px'};
            padding: ${props.padding ?? '0px'};
        `"
        :class="`hyperbloomui--link hyperbloomui--${state.hyperbloomui.theme.name}--link`"
        @click="$emit('click')"
    >
        <slot />
    </a>
</template>
