// src/components/TextBox.vue
<script setup>
    import { defineProps } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        padding: String
    });
</script>

<style lang="sass">
    .hyperbloomui--text-box
        display: block
        text-align: start
</style>

<template>
    <div
        aria-component-id="text-box"
        :style="`
            margin: ${props.margin ?? '0px'};
            padding: ${props.padding ?? '0px'};
        `"
        :class="`hyperbloomui--text-box hyperbloomui--${state.hyperbloomui.theme.name}--text-box`"
    >
        <slot />
    </div>
</template>

// src/components/TextBox.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let padding: string = '0px';

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--text-box
        display: block
        text-align: start
</style>

<div
    style:margin={margin}
    style:padding={padding}
    class={`
        hyperbloomui--text-box
        hyperbloomui--${currentTheme}--text-box
    `}
>
    <slot />
</div>
