// src/layouts/AccentContainer.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let padding: string = '0px';

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--accent-container
        display: block
        background-color: var(--hyperbloomui--colors--accent)
</style>

<div
    style:margin={margin}
    style:padding={padding}
    class={`
        hyperbloomui--accent-container
        hyperbloomui--${currentTheme}--accent-container
    `}
>
    <slot />
</div>

// src/layouts/AccentContainer.vue
<script setup>
    import { defineProps } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        padding: String
    });
</script>

<style lang="sass">
    .hyperbloomui--accent-container
        display: block
        background-color: var(--hyperbloomui--colors--accent)
</style>

<template>
    <div
        aria-component-id="accent-container"
        :style="`
            margin: ${props.margin ?? '0px'};
            padding: ${props.padding ?? '0px'};
        `"
        :class="`
            hyperbloomui--accent-container
            hyperbloomui--${state.hyperbloomui.theme.name}--accent-container
        `"
    >
        <slot />
    </div>
</template>
