// src/layouts/App.svelte
<script lang="ts">
    import { loadTheme } from '../themes/index';

    import state from '../state';

    export let theme: string | undefined = undefined;
    export let accentColor: string = 'black';

    let currentTheme: string | null = null;

    state.subscribe((state) => {
        currentTheme = state.hyperbloomui.theme.name;
        accentColor = state.hyperbloomui.theme.colors.accent;
    });

    $: loadTheme(theme)
        .then((name) => {
            state.update((state) => {
                state.hyperbloomui.theme.name = name;

                return state;
            });
        })
        .catch((err) => console.error(`Failed to load theme ${theme}: ${err}`));

    $: state.update((state) => {
        if (typeof(accentColor) === 'string')
            state.hyperbloomui.theme.colors.accent = accentColor;

        return state;
    });
</script>

<style lang="sass">
    .hyperbloomui--app
        width: 100%
        height: 100%
        margin: 0
        padding: 0

        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif
        font-size: 16px
</style>

<div
    style={`
        --hyperbloomui--colors--accent: ${accentColor}
    `}
    class={`
        hyperbloomui--app
        hyperbloomui--${currentTheme}--app
    `}
>
    <slot />
</div>

// src/layouts/App.vue
<script async setup>
    import { defineProps } from 'vue';
    import state from '../state';
    import { loadTheme } from '../themes/index';

    const props = defineProps({
        theme: String,
        accentColor: String
    });

    loadTheme(props.theme)
        .then((name) => state.hyperbloomui.theme.name = name)
        .catch((err) => console.error(`Failed to load theme ${props.theme}: ${err}`));

    if (typeof(props.accentColor) === 'string')
        state.hyperbloomui.theme.colors.accent = props.accentColor;
</script>

<style lang="sass">
    .hyperbloomui--app
        width: 100%
        height: 100%
        margin: 0
        padding: 0

        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif
        font-size: 16px
</style>

<template>
    <div
        :style="`--hyperbloomui--colors--accent: ${state.hyperbloomui.theme.colors.accent};`"
        :class="`hyperbloomui--app hyperbloomui--${state.hyperbloomui.theme.name}--app`"
    >
        <slot />
    </div>
</template>
