// src/layouts/Clamp.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let width: string = '600px';
    export let height: string = 'unset';

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--clamp-container
        display: flex
        align-items: center
        justify-content: center

        width: 100%
        height: 100%

        .hyperbloomui--clamp
            display: block

            width: 100%
            height: 100%
</style>

<div
    style:margin={margin}
    class={`
        hyperbloomui--clamp-container
        hyperbloomui--${currentTheme}--clamp-container
    `}
>
    <div
        style:max-width={width}
        style:max-height={height}
        class={`
            hyperbloomui--clamp
            hyperbloomui--${currentTheme}--clamp
        `}
    >
        <slot />
    </div>
</div>

// src/layouts/Clamp.vue
<script setup>
    import { defineProps } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        width: String,
        height: String
    });
</script>

<style lang="sass">
    .hyperbloomui--clamp-container
        display: flex
        align-items: center
        justify-content: center

        width: 100%
        height: 100%

        .hyperbloomui--clamp
            display: block

            width: 100%
            height: 100%
</style>

<template>
    <div
        aria-component-id="clamp-container"
        :style="`
            margin: ${props.margin ?? '0px'};
        `"
        :class="`
            hyperbloomui--clamp-container
            hyperbloomui--${state.hyperbloomui.theme.name}--clamp-container
        `"
    >
        <div
            aria-component-id="clamp"
            :style="`
                max-width: ${props.width ?? '600px'};
                max-height: ${props.height ?? 'unset'};
            `"
            :class="`
                hyperbloomui--clamp
                hyperbloomui--${state.hyperbloomui.theme.name}--clamp
            `"
        >
            <slot />
        </div>
    </div>
</template>
