// src/layouts/MutedContainer.svelte
<script lang="ts">
    import state from '../state';

    export let margin: string = '0px';
    export let padding: string = '0px';

    let currentTheme: string | null = null;

    state.subscribe((state) => currentTheme = state.hyperbloomui.theme.name);
</script>

<style lang="sass">
    .hyperbloomui--muted-container
        display: block
</style>

<div
    style:margin={margin}
    style:padding={padding}
    class={`
        hyperbloomui--muted-container
        hyperbloomui--${currentTheme}--muted-container
    `}
>
    <slot />
</div>

// src/layouts/MutedContainer.vue
<script setup>
    import { defineProps } from 'vue';
    import state from '../state';

    const props = defineProps({
        margin: String,
        padding: String
    });
</script>

<style lang="sass">
    .hyperbloomui--muted-container
        display: block
</style>

<template>
    <div
        aria-component-id="muted-container"
        :style="`
            margin: ${props.margin ?? '0px'};
            padding: ${props.padding ?? '0px'};
        `"
        :class="`hyperbloomui--muted-container hyperbloomui--${state.hyperbloomui.theme.name}--muted-container`"
    >
        <slot />
    </div>
</template>
